using Entities.Models;
using Repository.Contracts;

namespace Repository
{
    public class SongRepository : ISongRepository
    {
        public async Task<IEnumerable<Song>> GetSongsAsync(int artistId)
            => await Task.Run(() => Songs().Where(s => s.ArtistID.Equals(artistId)).ToList());       

        private static IEnumerable<Song> Songs()
        {
            return new List<Song>
            {
                new Song
                {
                    ArtistID =1,
                    Title="She Knows",
                    Lyrics ="Bad things happen to the people you love\r\nAnd you find yourself praying up to heaven above\r\nBut honestly I've never had much sympathy\r\nCause those bad things, I always saw them coming for me\r\nI'm gonna run run away, run run away, run away\r\nRun away and never come back\r\nRun run away, run run away, run away show ‘em that your color is black\r\n\r\nShe knows, she knows\r\nOh I, oh I-I-I\r\nAlright\r\nOh I, oh I-I-I\r\nAlright\r\n\r\nDamned if I do\r\nDamned if I don't\r\nYou know I got a girl back home\r\nYou got a man what you want, what you want\r\nWhat these bitches want from a nigga\r\nOn some DMX shit\r\nI know them other niggas love tricking\r\nOn some BMX shit\r\nBut not me\r\nNow I'm sure you done heard about me\r\nA black star, Mos Def, Kweli\r\nGood so them bad hoes try me, they try me\r\nThis is Martin Luther King in the club\r\nGetting dubs, with a bad bitch\r\nIn his ear sayin' that she down for whatever\r\nIn the back of his mind is Coretta\r\n\r\nShe knows, she knows\r\nAnd I know she knows, and I know she knows\r\nAnd deep down she knows, she knows\r\nAnd I know she knows, and I know she knows\r\nWell alright\r\nOh I, oh I-I-I\r\nI can't be what you want from me\r\nWell alright\r\nOh I, oh I-I-I\r\nI can't be what you want from me\r\nWell alright\r\n\r\nDamned if I do, damned if I don't\r\nI'm passing up on bad hoes\r\nTrying to be the man that she want, what she want\r\nWhat she want from a nigga\r\nTo put a ring on it\r\nGot a bitch on my dick right now\r\nAnd she just want to sing on it\r\nGot me up so high\r\nTrying to get a piece of that apple pie\r\nI be up so high\r\nTrying to get a piece of that apple pie\r\nDancehall vibes with my pants on fire\r\nCause I told her I was sleeping\r\nCause I creep with this pretty young thing that I chose\r\nThat she could be doing the same thing I suppose\r\n\r\nShe knows, she knows\r\nAnd I know she knows, and I know she knows\r\nAnd deep down she knows, she knows\r\nAnd I know she knows, and I know she knows\r\nWell alright\r\nOh I, oh I-I-I\r\nI can't be what you want from me\r\nWell alright\r\nOh I, oh I-I-I\r\nI can't be what you want from me\r\nWell alright\r\n\r\nNiggas say turn up, hoes say turn up\r\nOnly bad thing about a star is they burn up\r\nNiggas say turn up, hoes say turn up\r\nOnly bad thing about a star is they burn up\r\nRest in peace to Aaliyah\r\nRest in peace to Left Eye\r\nMichael Jackson, I'll see ya\r\nJust as soon as I die\r\n\r\nGot me up so high, trying to get a piece of that apple pie\r\nI be up so high, trying to get a piece of that apple pie\r\nGot me up so high, trying to get a piece of that apple pie\r\nI be up so high, trying to get a piece of that apple pie\r\n\r\nWell alright\r\nOh I, oh I-I-I\r\nI can't be what you want from me\r\nWell alright\r\nOh I, oh I-I-I\r\nI can't be what you want from me\r\nWell alright"
                },
                new Song
                {
                    ArtistID =1,
                    Title="Thriller",
                    Lyrics ="It's close to midnight and something evil's lurkin' in the dark\r\nUnder the moonlight you see a sight that almost stops your heart\r\nYou try to scream but terror takes the sound before you make it\r\nYou start to freeze as horror looks you right between the eyes,\r\nYou're paralyzed\r\n\r\n'Cause this is thriller, thriller night\r\nAnd no one's gonna save you from the beast about to strike\r\nYou know it's thriller, thriller night\r\nYou're fighting for your life inside a killer, thriller tonight\r\n\r\nYou hear the door slam and realize there's nowhere left to run\r\nYou feel the cold hand and wonder if you'll ever see the sun\r\nYou close your eyes and hope that this is just imagination, girl\r\nBut all the while you hear a creature creepin' up behind\r\nYou're outta time\r\n\r\n'Cause this is thriller, thriller night\r\nThere ain't no second chance against the thing with the forty eyes, girl\r\nThriller, thriller night\r\nYou're fighting for your life inside a killer, thriller tonight\r\n\r\nNight creatures call\r\nAnd the dead start to walk in their masquerade\r\nThere's no escaping the jaws of the alien this time (they're open wide)\r\nThis is the end of your life\r\n\r\nThey're out to get you, there's demons closing in on every side\r\nThey will possess you unless you change that number on your dial\r\nNow is the time for you and I to cuddle close together\r\nAll through the night I'll save you from the terror on the screen,\r\nI'll make you see\r\n\r\nThat this is thriller, thriller night\r\n'Cause I can thrill you more than any ghoul could ever dare try\r\nThriller, thriller night\r\nSo let me hold you tight and share a killer, thriller, chiller\r\nThriller here tonight\r\n\r\n'Cause this is thriller, thriller night\r\nGirl, I can thrill you more than any ghoul could ever dare try\r\nThriller, thriller night\r\nSo let me hold you tight and share a killer, thriller\r\n\r\nI'm gonna thrill you tonight\r\n\r\n[Vincent Price:]\r\nDarkness falls across the land\r\nThe midnight hour is close at hand\r\nCreatures crawl in search of blood\r\nTo terrorize y'all's neighborhood\r\nAnd whomsoever shall be found\r\nWithout the soul for getting down\r\nMust stand and face the hounds of hell\r\nAnd rot inside a corpse's shell\r\n\r\n[Michael Jackson:]\r\nI'm gonna thrill you tonight...\r\n\r\n[Vincent Price:]\r\nThe foulest stench is in the air\r\nThe funk of forty thousand years\r\nAnd grisly ghouls from every tomb\r\nAre closing in to seal your doom\r\nAnd though you fight to stay alive\r\nYour body starts to shiver\r\nFor no mere mortal can resist\r\nThe evil of the thriller"
                },
                new Song
                {
                    ArtistID =3,
                    Title="Delicate",
                    Lyrics ="This ain't for the best\r\nMy reputation's never been worse, so\r\nYou must like me for me\r\nWe can't make\r\nAny promises now, can we, babe?\r\nBut you can make me a drink\r\n\r\nDive bar on the East Side, where you at?\r\nPhone lights up my nightstand in the black\r\nCome here, you can meet me in the back\r\nDark jeans and your Nikes, look at you\r\nOh, damn, never seen that color blue\r\nJust think of the fun things we could do\r\n\r\n('Cause I like you) This ain't for the best\r\nMy reputation's never been worse, so\r\nYou must like me for me\r\n(Yeah, I want you) We can't make\r\nAny promises now, can we, babe?\r\nBut you can make me a drink\r\n\r\nIs it cool that I said all that?\r\nIs it chill that you're in my head?\r\n'Cause I know that it's delicate (Delicate)\r\nIs it cool that I said all that?\r\nIs it too soon to do this yet?\r\n'Cause I know that it's delicate\r\n\r\nIsn't it? Isn't it? Isn't it?\r\nIsn't it?\r\nIsn't it? Isn't it? Isn't it?\r\nIsn't it delicate?\r\n\r\nThird floor on the West Side, me and you\r\nHandsome, you're a mansion with a view\r\nDo the girls back home touch you like I do?\r\nLong night, with your hands up in my hair\r\nEchoes of your footsteps on the stairs\r\nStay here, honey, I don't wanna share\r\n\r\n('Cause I like you) This ain't for the best\r\nMy reputation's never been worse, so\r\nYou must like me for me\r\n(Yeah, I want you) We can't make\r\nAny promises now, can we, babe?\r\nBut you can make me a drink\r\n\r\nIs it cool that I said all that?\r\nIs it chill that you're in my head?\r\n'Cause I know that it's delicate (Delicate)\r\nIs it cool that I said all that?\r\nIs it too soon to do this yet?\r\n'Cause I know that it's delicate\r\n\r\nIsn't it? Isn't it? Isn't it?\r\nIsn't it?\r\nIsn't it? Isn't it? Isn't it?\r\nIsn't it delicate?\r\n\r\nSometimes, I wonder, when you sleep\r\nAre you ever dreaming of me?\r\nSometimes, when I look into your eyes\r\nI pretend you're mine all the damn time\r\n\r\n('Cause I like you)\r\nIs it cool that I said all that?\r\nIs it chill that you're in my head?\r\n'Cause I know that it's delicate (Delicate)\r\n(Yeah, I want you)\r\nIs it cool that I said all that?\r\nIs it too soon to do this yet?\r\n'Cause I know that it's delicate (Delicate)\r\n('Cause I like you)\r\nIs it cool that I said all that? (Isn't it?)\r\nIs it chill that you're in my head? (Isn't it? Isn't it?)\r\n'Cause I know that it's delicate (Isn't it delicate?)\r\n(Yeah, I want you)\r\nIs it cool that I said all that? (Isn't it?)\r\nIs it too soon to do this yet? (Isn't it? Isn't it?)\r\n'Cause I know that it's delicate\r\nIsn't it delicate?"
                },
                new Song
                {
                    ArtistID =3,
                    Title="Tim McGraw",
                    Lyrics ="He said the way my blue eyes shined\r\nPut those Georgia stars to shame that night\r\nI said, \"That's a lie\"\r\nJust a boy in a Chevy truck\r\nThat had a tendency of gettin' stuck\r\nOn back roads at night\r\nAnd I was right there beside him all summer long\r\nAnd then the time we woke up to find that summer gone\r\n\r\nBut when you think Tim McGraw\r\nI hope you think my favorite song\r\nThe one we danced to all night long\r\nThe moon like a spotlight on the lake\r\nWhen you think happiness\r\nI hope you think that little black dress\r\nThink of my head on your chest\r\nAnd my old faded blue jeans\r\nWhen you think Tim McGraw\r\nI hope you think of me\r\n\r\nSeptember saw a month of tears\r\nAnd thankin' God that you weren't here\r\nTo see me like that\r\nBut in a box beneath my bed\r\nIs a letter that you never read\r\nFrom three summers back\r\nIt's hard not to find it all a little bittersweet\r\nAnd lookin' back on all of that, it's nice to believe\r\n\r\nWhen you think Tim McGraw\r\nI hope you think my favorite song\r\nThe one we danced to all night long\r\nThe moon like a spotlight on the lake\r\nWhen you think happiness\r\nI hope you think that little black dress\r\nThink of my head on your chest\r\nAnd my old faded blue jeans\r\nWhen you think Tim McGraw\r\nI hope you think of me\r\n\r\nAnd I'm back for the first time since then\r\nI'm standin' on your street\r\nAnd there's a letter left on your doorstep\r\nAnd the first thing that you'll read is:\r\n\r\n\"When you think Tim McGraw\r\nI hope you think my favorite song\r\nSomeday you'll turn your radio on\r\nI hope it takes you back to that place\"\r\n\r\nWhen you think happiness\r\nI hope you think that little black dress\r\nThink of my head on your chest\r\nAnd my old faded blue jeans\r\nWhen you think Tim McGraw\r\nI hope you think of me\r\n\r\nOh, think of me\r\nMmmm\r\n\r\nHe said the way my blue eyes shined\r\nPut those Georgia stars to shame that night\r\nI said, \"That's a lie\"\r\n"
                }
            };      
        }
    }
}
